INSERT INTO `monolith`.`hormone_symptom_to_question` (`formId`, `questionRef`, `title`, `category`) VALUES

('MIP-H1', 'achesPains', 'Aches / Pains', 'Androgen Deficiency'),
('MIP-H1', 'achesPains', 'Aches / Pains', 'Cortisol Deficiency'),
('MIP-H1', 'achesPains', 'Aches / Pains', 'Thyroid Deficiency'),
('MIP-H1', 'acne', 'Acne', 'Androgen Excess'),
('MIP-H1', 'acne', 'Acne', 'Cortisol Excess'),
('MIP-H1', 'agitation', 'Agitation', 'Thyroid Excess'),
('MIP-H1', 'allergiesHRT', 'Allergies', 'Cortisol Deficiency'),
('MIP-H1', 'anxiety', 'Anxiety', 'Cortisol Excess'),
('MIP-H1', 'anxiety', 'Anxiety', 'Thyroid Excess'),
('MIP-H1', 'arthritis', 'Arthritis', 'Androgen Deficiency'),
('MIP-H1', 'arthritis', 'Arthritis', 'Cortisol Deficiency'),
('MIP-H1', 'boneLoss', 'Bone Loss', 'Androgen Deficiency'),
('MIP-H1', 'boneLoss', 'Bone Loss', 'Cortisol Excess'),
('MIP-H1', 'boneLoss', 'Bone Loss', 'Thyroid Deficiency'),
('MIP-H1', 'chemicalSensitivity', 'Chemical Sensitivity', 'Cortisol Deficiency'),
('MIP-H1', 'coldBodyTemperature', 'Cold Body Temperature', 'Cortisol Deficiency'),
('MIP-H1', 'coldBodyTemperature', 'Cold Body Temperature', 'Cortisol Excess'),
('MIP-H1', 'coldBodyTemperature', 'Cold Body Temperature', 'Thyroid Deficiency'),
('MIP-H1', 'coldHandsAndOrFeet', 'Cold Hands and/or Feet', 'Thyroid Deficiency'),
('MIP-H1', 'constipation', 'Constipation', 'Thyroid Deficiency'),
('MIP-H1', 'decreasedMuscleMass', 'Decreased Muscle Mass', 'Androgen Deficiency'),
('MIP-H1', 'decreasedMuscleMass', 'Decreased Muscle Mass', 'Cortisol Excess'),
('MIP-H1', 'decreasedMuscleMass', 'Decreased Muscle Mass', 'Thyroid Deficiency'),
('MIP-H1', 'decreasedSweating', 'Decreased Sweating', 'Thyroid Deficiency'),
('MIP-H1', 'depression', 'Depression', 'Androgen Deficiency'),
('MIP-H1', 'depression', 'Depression', 'Thyroid Deficiency'),
('MIP-H1', 'difficultyConcentrating', 'Difficulty Concentrating', 'Thyroid Deficiency'),
('MIP-H1', 'difficultyLosingWeight', 'Difficulty Losing Weight', 'Thyroid Deficiency'),
('MIP-H1', 'dryAndBrittleHair', 'Dry and Brittle Hair', 'Thyroid Deficiency'),
('MIP-H1', 'elevatedCholesterol', 'Elevated Cholesterol', 'Androgen Excess'),
('MIP-H1', 'elevatedCholesterol', 'Elevated Cholesterol', 'Cortisol Excess'),
('MIP-H1', 'elevatedCholesterol', 'Elevated Cholesterol', 'Thyroid Deficiency'),
('MIP-H1', 'excessiveBodyHair', 'Excessive Body Hair', 'Androgen Excess'),
('MIP-H1', 'excessiveBodyHair', 'Excessive Body Hair', 'Cortisol Excess'),
('MIP-H1', 'excessiveFacialHair', 'Excessive Facial Hair', 'Androgen Excess'),
('MIP-H1', 'excessiveFacialHair', 'Excessive Facial Hair', 'Cortisol Excess'),
('MIP-H1', 'fatigue', 'Fatigue', 'Androgen Deficiency'),
('MIP-H1', 'fatigue', 'Fatigue', 'Cortisol Deficiency'),
('MIP-H1', 'fatigue', 'Fatigue', 'Cortisol Excess'),
('MIP-H1', 'fatigue', 'Fatigue', 'Thyroid Deficiency'),
('MIP-H1', 'hairLoss', 'Hair Loss', 'Androgen Excess'),
('MIP-H1', 'hairLoss', 'Hair Loss', 'Cortisol Excess'),
('MIP-H1', 'hairLoss', 'Hair Loss', 'Thyroid Deficiency'),
('MIP-H1', 'headaches', 'Headaches', 'Cortisol Excess'),
('MIP-H1', 'heartPalpitations', 'Heart Palpitations', 'Androgen Deficiency'),
('MIP-H1', 'heartPalpitations', 'Heart Palpitations', 'Cortisol Deficiency'),
('MIP-H1', 'heartPalpitations', 'Heart Palpitations', 'Cortisol Excess'),
('MIP-H1', 'heartPalpitations', 'Heart Palpitations', 'Thyroid Deficiency'),
('MIP-H1', 'heartPalpitations', 'Heart Palpitations', 'Thyroid Excess'),
('MIP-H1', 'historyOfFibromyalgia', 'History of Fibromyalgia', 'Androgen Deficiency'),
('MIP-H1', 'hoarseness', 'Hoarseness', 'Thyroid Deficiency'),
('MIP-H1', 'hotFeelings', 'Hot Feelings', 'Thyroid Excess'),
('MIP-H1', 'incontinence', 'Incontinence', 'Androgen Deficiency'),
('MIP-H1', 'infertilityIssues', 'Infertility Problems', 'Thyroid Deficiency'),
('MIP-H1', 'Irritability', 'Irritability', 'Androgen Excess'),
('MIP-H1', 'Irritability', 'Irritability', 'Cortisol Deficiency'),
('MIP-H1', 'Irritability', 'Irritability', 'Cortisol Excess'),
('MIP-H1', 'lowBloodPressure', 'Low Blood Pressure', 'Thyroid Deficiency'),
('MIP-H1', 'lowLibido', 'Low Libido', 'Androgen Deficiency'),
('MIP-H1', 'lowLibido', 'Low Libido', 'Cortisol Excess'),
('MIP-H1', 'lowLibido', 'Low Libido', 'Thyroid Deficiency'),
('MIP-H1', 'memoryLapses', 'Memory Lapses', 'Androgen Deficiency'),
('MIP-H1', 'memoryLapses', 'Memory Lapses', 'Cortisol Excess'),
('MIP-H1', 'memoryLapses', 'Memory Lapses', 'Thyroid Deficiency'),
('MIP-H1', 'moodChanges', 'Mood Changes', 'Thyroid Deficiency'),
('MIP-H1', 'nailsBreakingbrittle', 'Nails Brittle Or Breaking', 'Thyroid Deficiency'),
('MIP-H1', 'oilySkin', 'Oily Skin', 'Androgen Excess'),
('MIP-H1', 'personalOrFamilialHistoryOfBreastCancer', 'Breast Cancer (Yourself or Family)', 'Androgen Excess'),
('MIP-H1', 'personalOrFamilialHistoryOfBreastCancer', 'Breast Cancer (Yourself or Family)', 'Cortisol Excess'),
('MIP-H1', 'perspiration', 'Perspiration', 'Thyroid Excess'),
('MIP-H1', 'rapidHeartRate', 'Rapid Heart Rate', 'Thyroid Excess'),
('MIP-H1', 'sleepDisturbances', 'Sleep Disturbances', 'Androgen Deficiency'),
('MIP-H1', 'sleepDisturbances', 'Sleep Disturbances', 'Cortisol Excess'),
('MIP-H1', 'sleepDisturbances', 'Sleep Disturbances', 'Thyroid Deficiency'),
('MIP-H1', 'slowedReflexes', 'Slowed Reflexes', 'Thyroid Deficiency'),
('MIP-H1', 'slowPulseRate', 'Slow Pulse Rate', 'Thyroid Deficiency'),
('MIP-H1', 'stress', 'Stress', 'Cortisol Deficiency'),
('MIP-H1', 'stress', 'Stress', 'Cortisol Excess'),
('MIP-H1', 'sugarCravings', 'Sugar Cravings', 'Cortisol Deficiency'),
('MIP-H1', 'sugarCravings', 'Sugar Cravings', 'Cortisol Excess'),
('MIP-H1', 'swellingPuffy', 'Swelling Puffy Eyes Or Face', 'Thyroid Deficiency'),
('MIP-H1', 'thinningPubicHair', 'Thinning Pubic Hair', 'Androgen Deficiency'),
('MIP-H1', 'thinningSkin', 'Thinning Skin', 'Androgen Deficiency'),
('MIP-H1', 'thinningSkin', 'Thinning Skin', 'Cortisol Excess'),
('MIP-H1', 'thinningSkin', 'Thinning Skin', 'Thyroid Deficiency'),
('MIP-H1', 'weightGain', 'Weight Gain', 'Cortisol Excess'),
('MIP-H1', 'weightGain', 'Weight Gain', 'Thyroid Deficiency'),
('MIP-H1', 'weightLoss', 'Weight Loss', 'Thyroid Excess'),

('MIP-H2', 'aches_pains', 'Aches / Pains', 'Androgen Deficiency'),
('MIP-H2', 'aches_pains', 'Aches / Pains', 'Cortisol Deficiency'),
('MIP-H2', 'aches_pains', 'Aches / Pains', 'Thyroid Deficiency'),
('MIP-H2', 'agitated', 'Agitated', 'Thyroid Excess'),
('MIP-H2', 'allergiesH2', 'Allergies', 'Cortisol Deficiency'),
('MIP-H2', 'arthritis', 'Arthritis', 'Cortisol Deficiency'),
('MIP-H2', 'bone_loss', 'Bone Loss', 'Androgen Deficiency'),
('MIP-H2', 'bone_loss', 'Bone Loss', 'Cortisol Excess'),
('MIP-H2', 'bone_loss', 'Bone Loss', 'Thyroid Deficiency'),
('MIP-H2', 'breast_cancer', 'Breast Cancer (Yourself or Family)', 'Androgen Excess'),
('MIP-H2', 'breast_cancer', 'Breast Cancer (Yourself or Family)', 'Cortisol Excess'),
('MIP-H2', 'chemical_sensitivity', 'Chemical Sensitivity', 'Cortisol Deficiency'),
('MIP-H2', 'cold_body_temperature', 'Cold Body Temperature', 'Cortisol Deficiency'),
('MIP-H2', 'cold_body_temperature', 'Cold Body Temperature', 'Cortisol Excess'),
('MIP-H2', 'cold_body_temperature', 'Cold Body Temperature', 'Thyroid Deficiency'),
('MIP-H2', 'cold_hands_feet', 'Cold Hands and/or Feet', 'Thyroid Deficiency'),
('MIP-H2', 'constipation', 'Constipation', 'Thyroid Deficiency'),
('MIP-H2', 'decreased_muscle_mass', 'Decreased Muscle Mass', 'Androgen Deficiency'),
('MIP-H2', 'decreased_muscle_mass', 'Decreased Muscle Mass', 'Cortisol Excess'),
('MIP-H2', 'decreased_muscle_mass', 'Decreased Muscle Mass', 'Thyroid Deficiency'),
('MIP-H2', 'decreased_sweating', 'Decreased Sweating', 'Thyroid Deficiency'),
('MIP-H2', 'difficulty_concentrating', 'Difficulty Concentrating', 'Thyroid Deficiency'),
('MIP-H2', 'dry_brittle_hair', 'Dry and Brittle Hair', 'Thyroid Deficiency'),
('MIP-H2', 'elevated_triglycerides', 'Elevated Triglycerides', 'Androgen Excess'),
('MIP-H2', 'elevated_triglycerides', 'Elevated Triglycerides', 'Cortisol Excess'),
('MIP-H2', 'elevated_triglycerides', 'Elevated Triglycerides', 'Thyroid Deficiency'),
('MIP-H2', 'excessive_body_Hair', 'Excessive Body Hair', 'Androgen Excess'),
('MIP-H2', 'excessive_facial_hair', 'Excessive Facial Hair', 'Androgen Excess'),
('MIP-H2', 'fatigue', 'Fatigue', 'Androgen Deficiency'),
('MIP-H2', 'fatigue', 'Fatigue', 'Cortisol Deficiency'),
('MIP-H2', 'fatigue', 'Fatigue', 'Cortisol Excess'),
('MIP-H2', 'fibromyalgia', 'Fibromyalgia', 'Androgen Deficiency'),
('MIP-H2', 'forgetful', 'Forgetful', 'Thyroid Deficiency'),
('MIP-H2', 'hair_loss_scalp', 'Hair Loss On Scalp', 'Androgen Excess'),
('MIP-H2', 'headaches', 'Headaches', 'Cortisol Excess'),
('MIP-H2', 'heart_palpitations', 'Heart Palpitations', 'Androgen Deficiency'),
('MIP-H2', 'heart_palpitations', 'Heart Palpitations', 'Cortisol Deficiency'),
('MIP-H2', 'heart_palpitations', 'Heart Palpitations', 'Cortisol Excess'),
('MIP-H2', 'heart_palpitations', 'Heart Palpitations', 'Thyroid Deficiency'),
('MIP-H2', 'heart_palpitations', 'Heart Palpitations', 'Thyroid Excess'),
('MIP-H2', 'hoarseness', 'Hoarseness', 'Thyroid Deficiency'),
('MIP-H2', 'hot_feelings', 'Hot Feelings', 'Thyroid Excess'),
('MIP-H2', 'incontinence', 'Incontinence', 'Androgen Deficiency'),
('MIP-H2', 'increased_acne', 'Increased Acne', 'Androgen Excess'),
('MIP-H2', 'increased_acne', 'Increased Acne', 'Cortisol Excess'),
('MIP-H2', 'infertility_problems', 'Infertility Problems', 'Thyroid Deficiency'),
('MIP-H2', 'irritable', 'Irritability', 'Androgen Excess'),
('MIP-H2', 'low_blood_pressure', 'Low Blood Pressure', 'Thyroid Deficiency'),
('MIP-H2', 'low_libido', 'Low Libido', 'Androgen Deficiency'),
('MIP-H2', 'low_libido', 'Low Libido', 'Cortisol Excess'),
('MIP-H2', 'low_libido', 'Low Libido', 'Thyroid Deficiency'),
('MIP-H2', 'memory_lapses', 'Memory Lapses', 'Androgen Deficiency'),
('MIP-H2', 'memory_lapses', 'Memory Lapses', 'Cortisol Excess'),
('MIP-H2', 'memory_lapses', 'Memory Lapses', 'Thyroid Deficiency'),
('MIP-H2', 'mood_changes', 'Mood Changes', 'Thyroid Deficiency'),
('MIP-H2', 'moody', 'Moody', 'Cortisol Deficiency'),
('MIP-H2', 'moody', 'Moody', 'Cortisol Excess'),
('MIP-H2', 'nails_breaking_brittle', 'Nails Brittle Or Breaking', 'Thyroid Deficiency'),
('MIP-H2', 'nervousness', 'Nervousness', 'Cortisol Excess'),
('MIP-H2', 'nervousness', 'Nervousness', 'Thyroid Excess'),
('MIP-H2', 'oily_skin', 'Oily Skin', 'Androgen Excess'),
('MIP-H2', 'rapid_heart_rate', 'Rapid Heart Rate', 'Thyroid Excess'),
('MIP-H2', 'sleep_disturbances', 'Sleep Disturbances', 'Androgen Deficiency'),
('MIP-H2', 'sleep_disturbances', 'Sleep Disturbances', 'Cortisol Excess'),
('MIP-H2', 'sleep_disturbances', 'Sleep Disturbances', 'Thyroid Deficiency'),
('MIP-H2', 'slow_pulse_rate', 'Slow Pulse Rate', 'Thyroid Deficiency'),
('MIP-H2', 'stress', 'Stress', 'Cortisol Deficiency'),
('MIP-H2', 'stress', 'Stress', 'Cortisol Excess'),
('MIP-H2', 'sugar_cravings', 'Sugar Cravings', 'Cortisol Deficiency'),
('MIP-H2', 'sugar_cravings', 'Sugar Cravings', 'Cortisol Excess'),
('MIP-H2', 'sweaty', 'Sweaty', 'Thyroid Excess'),
('MIP-H2', 'swelling_puffy_eyes_face', 'Swelling Puffy Eyes Or Face', 'Thyroid Deficiency'),
('MIP-H2', 'thinning_pubic_hair', 'Thinning Pubic Hair', 'Androgen Deficiency'),
('MIP-H2', 'thinning_skin', 'Thinning Skin', 'Androgen Deficiency'),
('MIP-H2', 'thinning_skin', 'Thinning Skin', 'Cortisol Excess'),
('MIP-H2', 'thinning_skin', 'Thinning Skin', 'Thyroid Deficiency'),
('MIP-H2', 'tired_or_exhausted', 'Tired Or Exhausted', 'Thyroid Deficiency'),
('MIP-H2', 'weight_gain', 'Weight Gain', 'Thyroid Deficiency'),
('MIP-H2', 'weight_loss', 'Weight Loss', 'Thyroid Excess'),
('MIP-H2', 'weight_loss_difficulty', 'Difficulty Losing Weight', 'Thyroid Deficiency');
